# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: GitHub build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SOURCE_DIR:   ${{ github.workspace }}
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1 - Install Qt
      uses: jurplel/install-qt-action@v3.3.0
      with:
        version: '6.6.3'
        host: 'linux'
        target: 'desktop'
        install-deps: 'true'
        modules: qtcharts qtpositioning qtwebchannel qtwebengine

    - name: TEST List Qt Versions
      run: |
        aqt list-qt linux desktop

    - name: TEST List Qt Archs
      run: |
        aqt list-qt linux desktop --arch 6.6.3

    - name: TEST List Qt Modules
      run: |
        aqt list-qt linux desktop --modules 6.6.3 gcc_64

    - name: 2 - Checkout
      uses: actions/checkout@v4

    - name: 3 - Create build dir
      run: |
        mkdir build

    - name: 4 - Compile
      run: |
        cmake .

